### ISSUE TITLE
Basic flash card management

### ISSUE THREAD

**Issue by Imacds** [cs480SnackOverflow/demo-web-project#3]
As a user, I need the capability of the server receiving flash cards from a client so that I can upload them
As a server, we need the capability of holding onto those flash cards, this can be simple right now either in a file or exclusively in RAM, to fulfil client requests
As a client, I need the server to have capability of sending flash cards back to a client that requests them so I can study with them

**Comment by iamdarkes** [comment]
Flashcards have a userId which associates them to a specific user and they are stored in an h2 database.
